### ISSUE TITLE
May I ask how the depth map is generated specifically

### ISSUE THREAD

**Issue by pengjianqiang** [PJLallen/D2GPLand#2]
I ran ”./LeReS/Minist_Test/tools/test_depth. py“ file in the AdelaiDepth project, but the results of the depth map from the test are too different from those in the given dataset, may I ask how the depth map in the dataset is generated specifically?

**Comment by cuiruize** [comment]
For depth generation, we use the "./LeReS/Minist_Test/tools/test_depth. py" with the resnext101 backbone. Please kindly follow the instructions of AdelaiDepth and run the command "python ./tools/test_depth.py --load_ckpt res101.pth --backbone resnext101" to generate depth maps. The results should be the generated files with "-depth_raw.png" as the suffixes. Thanks for your attention.
